// src/components/Specializations/Specializations.tsx
import withStyles from "isomorphic-style-loader/withStyles";
import React, { PureComponent } from "react";
import s from "./Specializations.css";

const Specialization = ({ title = "front-end", li = ["React", "Mobx", "Moment", "React Native", "Corodva"] }) => (
  <div className={s.specialization}>
    <div>{title.toUpperCase()}</div>
    <ul>
      {li.map((val) => (
        <li key={val}>
          <span>{val}</span>
        </li>
      ))}
    </ul>
  </div>
);

@withStyles(s)
export class Specializations extends PureComponent<any, any> {
  public render() {
    return (
      <section className={s.root}>
        <h1>{"Specializations".toUpperCase()}</h1>
        <div>
          <div className="purple">
            <Specialization
              title="Main"
              li={[
                "OOP",
                "SOLID",
                "Design patterns",
                "Software design",
                "Software architecture",
                "Typescript",
                "TSLint",
              ]}
            />
          </div>
          <div className="blue">
            <Specialization />
          </div>
          <div className="green">
            <Specialization
              title="back-end"
              li={["Node.js", "Real time system", "Message Queuing", "MongoDB", "Docker"]}
            />
          </div>
        </div>
      </section>
    );
  }
}

// src/Specializations.svelte
<script lang="typescript">
  import Specialization from "./Specialization.svelte";
</script>

<section class="root">
  <h1>{"Specializations".toUpperCase()}</h1>
  <div>
    <div className="purple">
      <Specialization
        title="Main"
        li={[
          "OOP",
          "SOLID",
          "Design patterns",
          "Software design",
          "Software architecture",
          "Typescript",
          "TSLint",
        ]}
      />
    </div>
    <div className="blue">
      <Specialization />
    </div>
    <div className="green">
      <Specialization
        title="back-end"
        li={["Node.js", "Real time system", "Message Queuing", "MongoDB", "Docker"]}
      />
    </div>
  </div>
</section>

<style lang="css">
  @import "./vars/index.css";

  .root {
    width: 100%;
    margin-bottom: 45rem;
  }

  .root > h1 {
    font-size: 14rem;
    font-family: var(--font-family);
    font-weight: 700;
    text-align: left;
    color: var(--color-text-section-h1);
    margin-bottom: 27rem;
  }

  .root > div {
    display: flex;
  }

  .root > div > div {
    width: 50%;
  }

  @media (width < 1024px) {
    .root {
      margin-bottom: 12rem;
    }
    .root > h1 {
      text-align: center;
      margin-bottom: 16rem;
    }
    .root > div {
      flex-direction: column;
    }

    .root > div > div {
      width: 100%;
    }
  }
</style>
